//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenOracle01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrudIlusionEntities : DbContext
    {
        public CrudIlusionEntities()
            : base("name=CrudIlusionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrdenDetail> OrdenDetails { get; set; }
        public virtual DbSet<OrderManufacture> OrderManufactures { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
